# This taskbook is exactly indentical to the JSON version, but using YAML payload.
# The aci_rest module simply converts the YAML payload into JSON before sending to the APIC.

# Using YAML as input is convenient when managing the payload e.g. from git.

- name: Push aci_model

  # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  # We define the delegate_to at the block-level
  delegate_to: localhost

  block:
  - name: Bind EPGs to domains
    # Domain Types: l2dom, phys, vmm
    aci_epg_to_domain:
      <<: *aci_login
      tenant: '{{ item.tenant_name }}'
      app_profile: '{{ item.tenant_app_name }}'
      epg: '{{ item.tenant_app_epg_name }}'
      domain: '{{ item.tenant_app_epg_domains_name | default(None) or omit }}'
      domain_type: '{{ item.tenant_app_epg_domains_type | default(None) or omit }}'
      vm_provider: '{{ item.tenant_app_epg_domains_vm_provider | default(None) or omit }}'
    with_items: '{{ aci_model_data|aci_listify("tenant","app","epg","domains") }}'