name: Send dispatch to pivot-aci-ansible repository
on:
  release:
    types: [published]
jobs:
  submit_repository_dispatch:
    name: Send repository dispatch trigger to pivot-aci-ansible repo
    runs-on: ubuntu-latest
    steps:
      - name: Send API call with Curl
        run: |
          curl \
            -X POST \
            -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pivot-sdn/aci-ansible-container/dispatches \
            -d '{"event_type":"docker-build"}'
